version: 2

project_name: conjur-in-go

before:
  hooks:
    - go mod tidy

builds:
  - id: conjurctl
    main: ./cmd/conjurctl
    binary: conjurctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    tags:
      - embed_migrations
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.ShortCommit}}
      - -X main.BuildDate={{.Date}}
archives:
  - id: compressed
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "conjurctl_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - CHANGELOG.md
  - id: binary
    formats:
      - binary
    name_template: "conjurctl_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  use: git
  filters:
    exclude:
      - ".*"

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest"
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - db/migrations
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: conjur-in-go
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
  mode: replace
