// Auto-generated by gen/encrypted_models/main.go
package model

import (
	"fmt"

	"gorm.io/gorm"

	"conjur-in-go/pkg/slosilo"
)

func (s *Secret) BeforeCreate(tx *gorm.DB) error {
	encrypt := s.getCipherForDb(tx).Encrypt
	plainValue := s.Value
	encryptedValue, err := encrypt([]byte(s.ResourceId), plainValue)
	if err != nil {
		return fmt.Errorf("Value encryption failed for ResourceId=%q", s.ResourceId)
	}
	s.Value = encryptedValue

	return nil
}

func (s *Secret) AfterFind(tx *gorm.DB) error {
	decrypt := s.getCipherForDb(tx).Decrypt
	encryptedValue := s.Value
	plainValue, err := decrypt([]byte(s.ResourceId), encryptedValue)
	if err != nil {
		return fmt.Errorf("Value decryption failed for ResourceId=%q", s.ResourceId)
	}
	s.Value = plainValue

	return nil
}

func (s *Secret) AfterCreate(tx *gorm.DB) error {
	decrypt := s.getCipherForDb(tx).Decrypt
	encryptedValue := s.Value
	plainValue, err := decrypt([]byte(s.ResourceId), encryptedValue)
	if err != nil {
		return fmt.Errorf("Value decryption failed for ResourceId=%q", s.ResourceId)
	}
	s.Value = plainValue

	return nil
}

func (s *Secret) getCipherForDb(tx *gorm.DB) slosilo.SymmetricCipher {
	cipher, ok := tx.Statement.Context.Value("cipher").(slosilo.SymmetricCipher)
	if !ok || cipher == nil {
		panic("no cipher in database context")
	}

	return cipher
}
